# Generated by fork-release.yml. Do not edit by hand.
# cli-fingerprint: 6b8435e0000f1550f0afe6a76b6f48b6f96c42c7d731685884d9b8d7aedaaf5f
class AnarlogCli < Formula
  desc "CLI and MCP server for Anarlog meeting notes"
  homepage "https://github.com/dave-atx/anarlog"
  version "1.4.26"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dave-atx/anarlog/releases/download/fork_v1.4.26/anarlog-cli-aarch64-apple-darwin.tar.gz"
      sha256 "f35bcf0db474db69e572918062854ec4967a1165559dfd3db62c445809141eb0"
    end
    on_intel do
      url "https://github.com/dave-atx/anarlog/releases/download/fork_v1.4.26/anarlog-cli-x86_64-apple-darwin.tar.gz"
      sha256 "8f1a2af73cbbed5c971b23818e02ba60fe3722b59b7e3cccb70d958ba28e5886"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dave-atx/anarlog/releases/download/fork_v1.4.26/anarlog-cli-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "8e9c7d8d8d95375f9f23f7d3eb1da4319b1ca7d4efcf91673f56c347b8e0e79c"
    end
    on_intel do
      url "https://github.com/dave-atx/anarlog/releases/download/fork_v1.4.26/anarlog-cli-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "bfab66f0bc5e0858703f04a69461132e1d55b64789cf7b21a069ca6452d97687"
    end
  end

  def install
    bin.install "anarlog"
  end

  test do
    assert_match "anarlog", shell_output("#{bin}/anarlog --version")
  end
end
