# Generated by fork-release.yml. Do not edit by hand.
# cli-fingerprint: 8f452d30a45063d88d20275f7a3a4e9b8b3a677b95240d56207615a7d27d2c0c
class AnarlogCli < Formula
  desc "CLI and MCP server for Anarlog meeting notes"
  homepage "https://github.com/dave-atx/anarlog"
  version "1.4.25"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dave-atx/anarlog/releases/download/fork_v1.4.25/anarlog-cli-aarch64-apple-darwin.tar.gz"
      sha256 "5e9729395756d5f5d1041803378e7d38e46532e19a1d43afcbae50ca86dc5e82"
    end
    on_intel do
      url "https://github.com/dave-atx/anarlog/releases/download/fork_v1.4.25/anarlog-cli-x86_64-apple-darwin.tar.gz"
      sha256 "bfa73df487b1f5af30199ba6fb3e01f1f3f9cb79f9f60c2ee6ad2e1ef8dcb852"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dave-atx/anarlog/releases/download/fork_v1.4.25/anarlog-cli-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c27cdba63ec51650d41be71ab18ae0b258929155540e08ec54fa5d8c8b2f69d1"
    end
    on_intel do
      url "https://github.com/dave-atx/anarlog/releases/download/fork_v1.4.25/anarlog-cli-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a8a8cad71a255742c2e1f0441a6582af59ecdf189a32b2eba1ef7a2e4841461b"
    end
  end

  def install
    bin.install "anarlog"
  end

  test do
    assert_match "anarlog", shell_output("#{bin}/anarlog --version")
  end
end
