# Generated by fork-release.yml. Do not edit by hand.
# cli-fingerprint: d2463b1aaa56f3019b89854150b6887fc266a32dd72da0f81e1fe335ad333926
class AnarlogCli < Formula
  desc "CLI and MCP server for Anarlog meeting notes"
  homepage "https://github.com/dave-atx/anarlog"
  version "1.4.27"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dave-atx/anarlog/releases/download/fork_v1.4.27/anarlog-cli-aarch64-apple-darwin.tar.gz"
      sha256 "dcf05f55a5751b83271b782566c09d84c430fa013f12d1c1aae89116d9669c9f"
    end
    on_intel do
      url "https://github.com/dave-atx/anarlog/releases/download/fork_v1.4.27/anarlog-cli-x86_64-apple-darwin.tar.gz"
      sha256 "f4d57852aa306b3fc0af188ee4d3188af4d24e2d74ade01705471b034c83752d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dave-atx/anarlog/releases/download/fork_v1.4.27/anarlog-cli-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "63d4c17df7319046e69af8c47805d4f13ad3c92c346efb4e668d02a40bec155a"
    end
    on_intel do
      url "https://github.com/dave-atx/anarlog/releases/download/fork_v1.4.27/anarlog-cli-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f91d6508ff0b227af40c458c4d84919fdf4da209ca674b31fe594f4475ff89f5"
    end
  end

  def install
    bin.install "anarlog"
  end

  test do
    assert_match "anarlog", shell_output("#{bin}/anarlog --version")
  end
end
